import { SAMPLE_TODAY, type Item } from "./types";

export const samples: Item[] = [
  {
    id: "harbor",
    kind: "invoice",
    counterparty: "Harbor & Co",
    amount: 6800,
    issuedOn: "2026-09-01",
    dueOn: "2026-09-25",
    text: "Acompte de conception, paiement à 15 jours. Nouveau client, répond vite.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "northwind",
    kind: "invoice",
    counterparty: "Northwind Studio",
    amount: 2400,
    issuedOn: "2026-08-20",
    dueOn: "2026-09-05",
    text: "Des nouvelles de la facture de mars ? On va peut-être repousser ça au trimestre prochain.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "kite",
    kind: "invoice",
    counterparty: "Kite & Co",
    amount: 1100,
    issuedOn: "2026-06-01",
    dueOn: "2026-07-01",
    text: "Arrêtez de m'écrire. Nous ne paierons pas cette facture.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "adobe",
    kind: "receipt",
    counterparty: "Adobe",
    amount: 59.99,
    issuedOn: "2026-09-20",
    dueOn: null,
    text: "Creative Cloud, abonnement logiciel.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "united",
    kind: "receipt",
    counterparty: "United",
    amount: 640,
    issuedOn: "2026-09-12",
    dueOn: null,
    text: "Vol pour une conférence client. Ils rembourseront peut-être une partie.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "foods",
    kind: "receipt",
    counterparty: "Whole Foods",
    amount: 86.2,
    issuedOn: "2026-09-18",
    dueOn: null,
    text: "Courses pour l'appartement.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "cafe",
    kind: "receipt",
    counterparty: "Cafe Maya",
    amount: 18.4,
    issuedOn: "2026-09-21",
    dueOn: null,
    text: "Café avec un client.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
];
