import { SAMPLE_TODAY, type Item } from "./types";

export const samples: Item[] = [
  {
    id: "harbor",
    kind: "invoice",
    counterparty: "Harbor & Co",
    amount: 6800,
    issuedOn: "2026-09-01",
    dueOn: "2026-09-25",
    text: "Design retainer, net 15. New client, replies quickly.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "northwind",
    kind: "invoice",
    counterparty: "Northwind Studio",
    amount: 2400,
    issuedOn: "2026-08-20",
    dueOn: "2026-09-05",
    text: "Any update on the March invoice? We might push this to next quarter.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "kite",
    kind: "invoice",
    counterparty: "Kite & Co",
    amount: 1100,
    issuedOn: "2026-06-01",
    dueOn: "2026-07-01",
    text: "Stop emailing me. We won't pay this invoice.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "adobe",
    kind: "receipt",
    counterparty: "Adobe",
    amount: 59.99,
    issuedOn: "2026-09-20",
    dueOn: null,
    text: "Creative Cloud, monthly software.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "united",
    kind: "receipt",
    counterparty: "United",
    amount: 640,
    issuedOn: "2026-09-12",
    dueOn: null,
    text: "Flight to a client conference. They may reimburse part of it.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "foods",
    kind: "receipt",
    counterparty: "Whole Foods",
    amount: 86.2,
    issuedOn: "2026-09-18",
    dueOn: null,
    text: "Groceries for the apartment.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
  {
    id: "cafe",
    kind: "receipt",
    counterparty: "Cafe Maya",
    amount: 18.4,
    issuedOn: "2026-09-21",
    dueOn: null,
    text: "Latte with a client.",
    source: "sample",
    asOf: SAMPLE_TODAY,
  },
];
